#%RAML 1.0
title: Cockpit API
baseUri: http://js8:5000
version: v1
mediaType:  application/json

types:
  Repository:
    properties:
      path:
          type: string
          required: false
      name:
          type: string
          required: true
    example:
        path: "/opt/code/github/jumscpale/cockpit"
        name: "cockpit"

  Blueprint:
    properties:
      name:
          type: string
          required: true
      content:
          type: string
          required: true
    example:
        name: "cockpit.yaml"
        content: |
            service__main:
                description: "a service"

  Service:
    properties:
        name: string
        instance: string
        actions_py: string
        state: string
        instance_hrd: string
    example:
        name: "github_repo"
        instance: "main"
        actions_py: |
                class Actions(ActionsBaseMgmt):
                    @action()
                    def foor(self):
                        print('do something')
        state: |
            events: {}
            instanceHRDHash: 935b56207178ba811cba2eb11a7bb834
            parent: ''
            producers:
              github_client: [github_client!main]
            recipe: github_account
            recurring: {}
            state:
              init: [OK, 1462881794]
              install: [OK, 1462881573]
            templateHRDHash: ''
        instance_hrd: |
              github.client                  =
              github.url                     = 'https://github.com/zaibon'

  Template:
    properties:
        name:
            type: string
            required: true
        actions_py:
            type: string
            required: true
        schema_hrd:
            type: string
            required: true
    example:
        name: "github_repo"
        actions_py: |
                class Actions(ActionsBaseMgmt):
                    @action()
                    def foor(self):
                        print('do something')
        schema_hrd: |
            repo.name = type:'str' descr:'name of repo' @ASK
            repo.url = type:'str' descr:'url of github repo' default:''
            repo.account = parent:'github_account' @ASK
            repo.type =  type:'str' descr:'proj,code,ays,doc,user' @ASK
            code.path = type:'str' default:""
            github.client = type:'str' consume:'github_client:1' auto
            github.config= type:'str' consume:'github_config:1' auto
            milestone.category = type:'str' list
            milestones = type:'str' list consume:'github_milestone'
  Error:
    properties:
        code: integer
        error: string
    example:
        code: 404
        error: "repository not found"

/ays:
    /repository:
        description: a repository
        get:
            description: list all repositorys
            responses:
                200:
                    body:
                        application/json:
                          type: Repository[]
        post:
            description: create a new repository
            body:
                application/json:
                    type: Repository
            responses:
                201:
                    description:
                        repository created
                    body:
                        application/json:
                          type: Repository
                409:
                    description: Repository with this name already exists.
                    body:
                        application/json:
                          type: Error
        /{repository}:
            uriParameters:
                repository:
                  type: string
            get:
                description: Get information of a repository
                responses:
                    200:
                        description: Detail of  a repository
                        body:
                            application/json:
                              type: Repository
                    404:
                        description: Repository not found
                        body:
                            application/json:
                              type: Error
            delete:
                description: Delete a repository
                responses:
                    204:
                        description: Repository removed
                    404:
                        description: Repository not found
                        body:
                            application/json:
                              type: Error

            /blueprint:
                description: A blueprint inside a repository
                get:
                    description: List all blueprint
                    responses:
                        200:
                            body:
                                application/json:
                                  type: Blueprint
                        404:
                            description: Blueprint not found
                            body:
                                application/json:
                                    type: Error

                post:
                    description: Create a new blueprint
                    body:
                        application/json:
                            properties:
                                type: Blueprint
                    responses:
                        201:
                            body:
                                application/json:
                                  type: Blueprint
                        409:
                            description: Blueprint with this name already exists
                            body:
                                application/json:
                                  type: Error
                /{blueprint}:
                    uriParameters:
                        blueprint:
                          type: string
                    get:
                        description: Get a blueprint
                        responses:
                            200:
                                body:
                                    application/json:
                                      type: Blueprint
                            404:
                                description: Blueprint not found
                                body:
                                    application/json:
                                      type: Error
                    post:
                        description: Execute the blueprint
                        responses:
                            200:

                    delete:
                        description: delete blueprint
                        responses:
                            204:
                                description: blueprint removed
                            404:
                                description: blueprint not found
                                body:
                                    application/json:
                                      type: Error

            /service:
                description: A service
                get:
                    description: List all services in the repository
                    responses:
                        200:
                            body:
                                application/json:
                                  type: Service[]
                /{role}:
                    uriParameters:
                        role:
                          type: string
                    get:
                        description: List all services of role 'role' in the repository
                        responses:
                            200:
                                body:
                                    application/json:
                                      type: Service[]
                    /action:
                        /{action}:
                            uriParameters:
                                action:
                                  type: string
                            post:
                                description: Perform an action on all service with the role 'role'
                                queryParameters:
                                    args:
                                        description: argument to pass to the action
                                        type: string[]
                                responses:
                                    200:
                                        description: action started
                                    404:
                                        description: not action with this name found for this service
                                        body:
                                            application/json:
                                              type: Error
                    /{instance}:
                        uriParameters:
                            instance:
                              type: string
                        get:
                            description: Get a service instance
                            responses:
                                200:
                                    body:
                                        application/json:
                                          type: Service
                                404:
                                    description: Service instance not found
                                    body:
                                        application/json:
                                          type: Error
                        /action:
                            get:
                                description: Get list of action available on this service
                                responses:
                                    200:
                                        body:
                                            application/json:
                                              type: string[]
                                    404:
                                        description: Service instance not found
                                        body:
                                            application/json:
                                              type: Error
                        /{action}:
                            uriParameters:
                                action:
                                  type: string
                            post:
                                description: Perform an action on a services
                                queryParameters:
                                    args:
                                        description: argument to pass to the action
                                        type: string[]
                                responses:
                                    200:
                                        description: action started
                                    404:
                                        description: Service instance not found
                                        body:
                                            application/json:
                                              type: Error

            /template:
                description: A template of a service
                get:
                    description: list all templates
                    responses:
                        200:
                            body:
                                application/json:
                                  type: Template[]
                post:
                    description: Create new template
                    body:
                        application/json:
                            type: Template
                    responses:
                        201:
                            body:
                                application/json:
                                  type: Template
                /{template}:
                    uriParameters:
                        template:
                          type: string
                    get:
                        description: Get a template
                        responses:
                            200:
                                body:
                                    application/json:
                                      type: Template
                            404:
                                body:
                                    application/json:
                                      type: Error
/webhooks:
    description:
    /github:
        post:
            description: Endpoint that receives the events from github
            responses:
                200:
                    description: event saved
                    body:
                        application/json:

/oauth:
    /callback:
        get:
            description: Callback endpoint for oauth
            responses:
                200:
                    body:
                        application/json:
